"use strict";
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { mutableDataPath } = require("../runtimePaths");
const FEATURE_STORE_VERSION = "mlb-pregame-feature-store-v1";
const QUALITY_FLAGS = new Set(["known", "partial", "unknown", "stale"]);
function parseTime(value, label) { const time = Date.parse(value || ""); if (!Number.isFinite(time)) throw new Error(`${label} must be an ISO timestamp`); return time; }
function assertTimedFeature(feature, name = "feature") { if (!feature || typeof feature !== "object" || !feature.source) throw new Error(`${name} must include a source`); parseTime(feature.observedAt, `${name}.observedAt`); parseTime(feature.availableAt, `${name}.availableAt`); if (!QUALITY_FLAGS.has(feature.quality)) throw new Error(`${name}.quality must be known, partial, unknown, or stale`); return true; }
function assertPregameFeatureSnapshot(snapshot) { if (!snapshot || snapshot.contract !== FEATURE_STORE_VERSION) throw new Error("Unsupported baseball feature-store snapshot contract"); const capturedAt = parseTime(snapshot.capturedAt, "capturedAt"); if (capturedAt >= parseTime(snapshot.firstPitchUtc, "firstPitchUtc")) throw new Error("Feature-store snapshot must be captured strictly before first pitch"); if (!snapshot.gameId || !snapshot.homeTeam || !snapshot.awayTeam) throw new Error("Feature-store snapshot is missing game identity"); for (const [name, feature] of Object.entries(snapshot.features || {})) { assertTimedFeature(feature, `features.${name}`); if (parseTime(feature.observedAt, `features.${name}.observedAt`) > capturedAt || parseTime(feature.availableAt, `features.${name}.availableAt`) > capturedAt) throw new Error(`Feature was not available at snapshot capture: ${name}`); } return true; }
function stableJson(value) { if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`; if (!value || typeof value !== "object") return JSON.stringify(value); return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`; }
function contentKey(value) { return crypto.createHash("sha256").update(stableJson(value)).digest("hex"); }
function writeImmutableJson(filePath, value) { if (fs.existsSync(filePath)) return { filePath, created: false }; fs.mkdirSync(path.dirname(filePath), { recursive: true }); fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, { flag: "wx" }); return { filePath, created: true }; }
function rawResponseRecord({ sourceUrl, fetchedAt, payload }) { parseTime(fetchedAt, "fetchedAt"); if (!sourceUrl) throw new Error("Raw response is missing sourceUrl"); return { contract: "mlb-raw-response-v1", sport: "baseball", league: "MLB", sourceUrl, fetchedAt, payload }; }
function normalizeSchedule(raw) { if (!raw || raw.contract !== "mlb-raw-response-v1") throw new Error("Expected an mlb-raw-response-v1 record"); return (raw.payload?.dates || []).flatMap((day) => (day.games || []).map((game) => { const observedAt = raw.fetchedAt; return { contract: "mlb-scheduled-game-v1", gameId: `mlb:${game.gamePk}`, sport: "baseball", league: "MLB", firstPitchUtc: game.gameDate || "", homeTeam: game.teams?.home?.team?.name || "", awayTeam: game.teams?.away?.team?.name || "", status: game.status?.detailedState || "Scheduled", venue: game.venue?.name || "", schedule: { value: { date: day.date || "", status: game.status?.abstractGameState || "" }, source: raw.sourceUrl, observedAt, availableAt: observedAt, quality: "known" } }; })).filter((game) => game.gameId && game.firstPitchUtc && game.homeTeam && game.awayTeam); }
function unknownFeature(source, capturedAt) { return { value: null, source, observedAt: capturedAt, availableAt: capturedAt, quality: "unknown" }; }
function buildPregameSnapshot(game, capturedAt) { const source = game.schedule.source; const snapshot = { contract: FEATURE_STORE_VERSION, snapshotId: `${game.gameId}:${capturedAt}`, gameId: game.gameId, firstPitchUtc: game.firstPitchUtc, capturedAt, homeTeam: game.homeTeam, awayTeam: game.awayTeam, features: { teamForm: unknownFeature(source, capturedAt), startingPitchers: unknownFeature(source, capturedAt), bullpen: unknownFeature(source, capturedAt), lineup: unknownFeature(source, capturedAt), park: { value: { venue: game.venue }, source, observedAt: capturedAt, availableAt: capturedAt, quality: game.venue ? "partial" : "unknown" }, weather: unknownFeature(source, capturedAt), travelRest: unknownFeature(source, capturedAt), gameStatus: { value: game.status, source, observedAt: capturedAt, availableAt: capturedAt, quality: "known" } } }; assertPregameFeatureSnapshot(snapshot); return snapshot; }
function ingestSchedulePayload({ payload, sourceUrl, fetchedAt = new Date().toISOString(), root = mutableDataPath("baseball", "feature_store") } = {}) { const raw = rawResponseRecord({ payload, sourceUrl, fetchedAt }); const key = contentKey(raw); const rawWrite = writeImmutableJson(path.join(root, "raw", "mlb-schedule", `${key}.json`), raw); const games = normalizeSchedule(raw); const normalizedWrite = writeImmutableJson(path.join(root, "normalized", "mlb-schedule", `${key}.json`), { contract: "mlb-normalized-schedule-v1", sourceRawKey: key, normalizedAt: fetchedAt, games }); return { rawKey: key, gameCount: games.length, rawPath: rawWrite.filePath, normalizedPath: normalizedWrite.filePath, created: rawWrite.created || normalizedWrite.created }; }
function capturePregameSnapshots({ normalizedSchedule, capturedAt = new Date().toISOString(), root = mutableDataPath("baseball", "feature_store") } = {}) { const games = normalizedSchedule?.games || []; const snapshots = []; for (const game of games) { if (parseTime(capturedAt, "capturedAt") >= parseTime(game.firstPitchUtc, "firstPitchUtc")) continue; const snapshot = buildPregameSnapshot(game, capturedAt); const result = writeImmutableJson(path.join(root, "snapshots", game.gameId.replace(/[^a-zA-Z0-9:_-]/g, "_"), `${contentKey(snapshot)}.json`), snapshot); snapshots.push({ gameId: game.gameId, ...result }); } return { capturedAt, attempted: games.length, captured: snapshots.length, snapshots }; }
function buildCollectedSnapshot(game, capturedAt, features = {}) {
  const source = game.schedule.source;
  const defaultFeatures = buildPregameSnapshot(game, capturedAt).features;
  const snapshot = {
    contract: FEATURE_STORE_VERSION, snapshotId: `${game.gameId}:${capturedAt}`, gameId: game.gameId,
    firstPitchUtc: game.firstPitchUtc, capturedAt, homeTeam: game.homeTeam, awayTeam: game.awayTeam,
    features: { ...defaultFeatures, ...features },
  };
  assertPregameFeatureSnapshot(snapshot);
  return snapshot;
}
module.exports = { FEATURE_STORE_VERSION, assertTimedFeature, assertPregameFeatureSnapshot, rawResponseRecord, normalizeSchedule, buildPregameSnapshot, buildCollectedSnapshot, ingestSchedulePayload, capturePregameSnapshots, contentKey, writeImmutableJson };
