"use strict";
const fs = require("fs"); const path = require("path");
const { mutableDataPath } = require("../runtimePaths");
const { assessPredictionReadiness } = require("./readiness");
const { predictBaseballGame } = require("./pipeline");
const { noVigMoneyline } = require("./odds");

function storePath(root = mutableDataPath("baseball")) { return path.join(root, "prediction_records.json"); }
function readRecords(root) { const file = storePath(root); try { return JSON.parse(fs.readFileSync(file, "utf8")); } catch { return { contract: "baseball-prediction-records-v1", records: [] }; } }
function writeRecords(data, root) { const file = storePath(root); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`); }
function toModelSnapshot(snapshot) {
  const form = snapshot.features.teamForm?.value;
  if (!form?.home?.season || !form?.away?.season) throw new Error("Snapshot has no usable team-form features");
  const rating = (side) => 100 * Number(side.season.runsForPerGame || 4.4) / 4.4;
  return { gameId: snapshot.gameId, firstPitchUtc: snapshot.firstPitchUtc, capturedAt: snapshot.capturedAt, homeTeam: snapshot.homeTeam, awayTeam: snapshot.awayTeam, home: { offenseRating: rating(form.home), startingPitcherRating: 100, bullpenRating: 100, lineupRating: 100, restDays: 1 }, away: { offenseRating: rating(form.away), startingPitcherRating: 100, bullpenRating: 100, lineupRating: 100, restDays: 1 }, park: { runFactor: 1 }, weather: {} };
}
function predictionMetadata(snapshot, prediction) { const starters = snapshot.features?.startingPitchers?.value || {}; const pitcherStatus = starters.home || starters.away ? "published" : "unavailable"; return { season: String(snapshot.firstPitchUtc || "").slice(0, 4) || "unknown", homeTeam: snapshot.homeTeam, awayTeam: snapshot.awayTeam, venue: snapshot.features?.park?.value?.venue || "unknown", pitcherStatus, market: prediction.probabilities.marketHomeWin == null ? "model-only" : prediction.probabilities.marketBlendApplied ? "market-blended" : "market-unblended" }; }
function createPrediction({ snapshot, model, odds, calibration, backtestBet, root }) {
  const health = monitoring(root); if (health.predictionStatus === "disabled") return { accepted: false, status: 503, reason: "Prediction service disabled by drift guard", monitoring: health };
  const readiness = assessPredictionReadiness(snapshot);
  if (!readiness.ready) return { accepted: false, status: 409, readiness };
  const prediction = predictBaseballGame(model, toModelSnapshot(snapshot), { odds, marketCalibration: calibration });
  const data = readRecords(root); const id = `baseball:${snapshot.gameId}:${snapshot.capturedAt}`;
  if (!data.records.some((record) => record.id === id)) { const bet = backtestBet?.side && Number(backtestBet.stake) > 0 && Number(backtestBet.decimalOdds) > 1 ? { side: backtestBet.side, stake: Number(backtestBet.stake), decimalOdds: Number(backtestBet.decimalOdds) } : null; data.records.push({ id, createdAt: new Date().toISOString(), snapshotId: snapshot.snapshotId, firstPitchUtc: snapshot.firstPitchUtc, metadata: predictionMetadata(snapshot, prediction), prediction, marketAtPrediction: noVigMoneyline(odds), backtestBet: bet, settlement: null }); writeRecords(data, root); }
  return { accepted: true, status: 201, id, prediction, readiness };
}
function settlePrediction(id, { homeRuns, awayRuns, closingOdds }, root) { const data = readRecords(root); const record = data.records.find((item) => item.id === id); if (!record) throw new Error("Prediction record not found"); if (!Number.isFinite(Number(homeRuns)) || !Number.isFinite(Number(awayRuns))) throw new Error("Final homeRuns and awayRuns are required"); const homeWon = Number(homeRuns) > Number(awayRuns); const closingMarket = noVigMoneyline(closingOdds); const betWon = record.backtestBet ? (record.backtestBet.side === "home" ? homeWon : !homeWon) : null; const profit = record.backtestBet ? (betWon ? record.backtestBet.stake * (record.backtestBet.decimalOdds - 1) : -record.backtestBet.stake) : null; const closingDecimal = record.backtestBet ? (record.backtestBet.side === "home" ? closingMarket?.homeDecimal : closingMarket?.awayDecimal) : null; record.settlement = { settledAt: new Date().toISOString(), homeRuns: Number(homeRuns), awayRuns: Number(awayRuns), homeWon, closingMarket, backtest: record.backtestBet ? { won: betWon, profit, closingDecimal, closingLineValue: closingDecimal ? record.backtestBet.decimalOdds - closingDecimal : null } : null }; writeRecords(data, root); return record; }
function scoreRows(records) { return records.filter((record) => record.settlement).map((record) => ({ probability: record.prediction.probabilities.blendedHomeWin, outcome: Number(record.settlement.homeWon), record })); }
function scoreSummary(rows) { if (!rows.length) return { predictions: 0, logLoss: null, brier: null }; return { predictions: rows.length, logLoss: rows.reduce((sum, row) => sum - Math.log(row.outcome ? row.probability : 1 - row.probability), 0) / rows.length, brier: rows.reduce((sum, row) => sum + (row.outcome - row.probability) ** 2, 0) / rows.length }; }
function calibrationCurve(rows) { const bins = Array.from({ length: 10 }, (_, bin) => ({ bin, predictions: 0, probability: 0, outcomes: 0 })); rows.forEach((row) => { const bin = bins[Math.min(9, Math.floor(row.probability * 10))]; bin.predictions += 1; bin.probability += row.probability; bin.outcomes += row.outcome; }); return bins.filter((bin) => bin.predictions).map((bin) => ({ bin: bin.bin, predictions: bin.predictions, averageProbability: bin.probability / bin.predictions, empiricalWinRate: bin.outcomes / bin.predictions })); }
function breakdown(rows, select) { const groups = new Map(); rows.forEach((row) => { for (const key of select(row.record)) { const group = groups.get(key) || []; group.push(row); groups.set(key, group); } }); return Object.fromEntries([...groups].sort(([a], [b]) => a.localeCompare(b)).map(([key, values]) => [key, scoreSummary(values)])); }
function monitoring(root) { const records = readRecords(root).records; const scored = scoreRows(records); const featureStore = path.join(root || mutableDataPath("baseball"), "feature_store", "snapshots"); let latestSnapshotAt = null; try { const times = fs.readdirSync(featureStore, { recursive: true }).filter((file) => file.endsWith(".json")).map((file) => fs.statSync(path.join(featureStore, file)).mtimeMs); if (times.length) latestSnapshotAt = new Date(Math.max(...times)).toISOString(); } catch {} let baseline = null; try { baseline = JSON.parse(fs.readFileSync(path.join(root || mutableDataPath("baseball"), "chronological_backtest.json"), "utf8")).metrics?.poisson; } catch {} const drift = scored.length >= 30 && baseline ? { detected: scoreSummary(scored).brier > baseline.brier + 0.05 || scoreSummary(scored).logLoss > baseline.logLoss + 0.1, baseline } : { detected: false, reason: "Insufficient settled predictions or baseline report" }; const betRecords = records.filter((record) => record.settlement?.backtest && record.backtestBet); const profit = betRecords.reduce((sum, record) => sum + record.settlement.backtest.profit, 0); const stake = betRecords.reduce((sum, record) => sum + record.backtestBet.stake, 0); const clv = betRecords.map((record) => record.settlement.backtest.closingLineValue).filter(Number.isFinite); return { contract: "baseball-monitoring-v1", predictionStatus: drift.detected ? "disabled" : "available", recordedPredictions: records.length, settledPredictions: scored.length, pendingPredictions: records.length - scored.length, modelOnlyPredictions: records.filter((record) => !record.prediction.probabilities.marketBlendApplied).length, latestSnapshotAt, drift, backtestBets: { settled: betRecords.length, stake, profit, roi: stake ? profit / stake : null, averageClosingLineValue: clv.length ? clv.reduce((sum, value) => sum + value, 0) / clv.length : null }, performance: { ...scoreSummary(scored), calibrationCurve: calibrationCurve(scored), breakdowns: { season: breakdown(scored, (record) => [record.metadata?.season || "unknown"]), team: breakdown(scored, (record) => [record.metadata?.homeTeam || "unknown", record.metadata?.awayTeam || "unknown"]), pitcherStatus: breakdown(scored, (record) => [record.metadata?.pitcherStatus || "unknown"]), venue: breakdown(scored, (record) => [record.metadata?.venue || "unknown"]), market: breakdown(scored, (record) => [record.metadata?.market || "unknown"]) } } }; }
module.exports = { createPrediction, settlePrediction, monitoring };
