"use strict";
// Converts immutable raw football-data.co.uk CSV artifacts into the canonical
// team-perspective artifact consumed by `ingest:team-history`.
const fs = require("fs"); const path = require("path");
const { normalizeTeamName } = require("../src/footballData");
function parseCsv(text) { const rows = []; let row = []; let cell = ""; let quoted = false; for (let i = 0; i < text.length; i += 1) { const c = text[i]; const next = text[i + 1]; if (c === '"') { if (quoted && next === '"') { cell += c; i += 1; } else quoted = !quoted; } else if (c === "," && !quoted) { row.push(cell); cell = ""; } else if ((c === "\n" || c === "\r") && !quoted) { if (c === "\r" && next === "\n") i += 1; row.push(cell); if (row.some(Boolean)) rows.push(row); row = []; cell = ""; } else cell += c; } if (cell || row.length) { row.push(cell); rows.push(row); } return rows; }
function iso(value) { const [day, month, year] = String(value || "").split(/[/-]/).map(Number); if (!day || !month || !year) return ""; const fullYear = year < 100 ? (year >= 50 ? year + 1900 : year + 2000) : year; return new Date(Date.UTC(fullYear, month - 1, day)).toISOString().slice(0, 10); }
const manifestPath = path.join("data", "teams", "history", "raw", "football-data-manifest.json"); const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")); const matches = [];
for (const source of manifest.rows.filter((row) => row.captured)) { const rows = parseCsv(fs.readFileSync(source.file, "utf8").replace(/^\uFEFF/, "")); const headers = rows.shift() || []; for (const values of rows) { const row = Object.fromEntries(headers.map((header, index) => [header, values[index] || ""])); const home = normalizeTeamName(row.HomeTeam); const away = normalizeTeamName(row.AwayTeam); const homeGoals = Number(row.FTHG); const awayGoals = Number(row.FTAG); const date = iso(row.Date); if (!home || !away || !date || !Number.isFinite(homeGoals) || !Number.isFinite(awayGoals)) continue; const key = `${source.sha256}:${date}:${encodeURIComponent(home)}:${encodeURIComponent(away)}`; const common = { date, season: source.season, competition: { name: source.competition, type: "league" }, source: { provider: "football-data.co.uk", url: source.url, retrievedAt: source.capturedAt } }; matches.push({ ...common, id: `football-data:${key}:home`, team: home, opponent: away, venue: "home", score: { for: homeGoals, against: awayGoals } }, { ...common, id: `football-data:${key}:away`, team: away, opponent: home, venue: "away", score: { for: awayGoals, against: homeGoals } }); } }
const output = path.join("data", "teams", "history", "normalized", `football-data-${Date.now()}.json`); fs.mkdirSync(path.dirname(output), { recursive: true }); fs.writeFileSync(output, JSON.stringify({ contract: "football-history-normalized-artifact-v1", generatedAt: new Date().toISOString(), sourceManifest: manifestPath, matches }, null, 2) + "\n"); console.log(JSON.stringify({ output, matches: matches.length }, null, 2));
